............/usr/local/lib/python3.4/site-packages/pandas-0.14.1-py3.4-linux-x86_64.egg/pandas/core/index.py:1023: RuntimeWarning: unorderable types: str() < int(), sort order is undefined for incomparable objects
  "incomparable objects" % e, RuntimeWarning)
/usr/local/lib/python3.4/site-packages/pandas-0.14.1-py3.4-linux-x86_64.egg/pandas/core/index.py:1023: RuntimeWarning: unorderable types: int() < str(), sort order is undefined for incomparable objects
  "incomparable objects" % e, RuntimeWarning)
../usr/local/lib/python3.4/site-packages/pandas-0.14.1-py3.4-linux-x86_64.egg/pandas/core/index.py:1037: RuntimeWarning: unorderable types: str() > int(), sort order is undefined for incomparable objects
  "incomparable objects" % e, RuntimeWarning)
/usr/local/lib/python3.4/site-packages/pandas-0.14.1-py3.4-linux-x86_64.egg/pandas/core/index.py:1037: RuntimeWarning: unorderable types: int() > str(), sort order is undefined for incomparable objects
  "incomparable objects" % e, RuntimeWarning)
.....................................................................................................................................................................................................................................................................S...........................FS...S.S....SSS...............................................S....................SS..........................S.....S....................S..........................S.....S.....................S..........................S.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS........E.................................S.EE....................................................................................................................................................S..........S................................................................................................................................................................S...........................................................................................................................................................................................................S....................................................................SS.....SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS......................................................S.............................SSSSSSSSSSS....................................S.S.......................................................................................................................................................S..................................S..................S..S.SSSSSSS...........................S...........................S.....SSSSSSSSSSSSSSSSSSSSSSSSSS..................................................................................................................................................................S.....................................................................................................................................S..S..............................................................................................................................................................................S...S.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................S..........................................................................................................................................................................................................................................................................................................................S............................................................................................................S............................................................................................................................................/usr/local/lib/python3.4/site-packages/numpy/core/_methods.py:55: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
......................................................................................................................................................................................................................................................................................................................S..............................................................................................................................................................................................................................................................................................................SS.....S...SS.......S.S.......................SS.....S...SS.......S.S..............SS..SS.......................................................................S......................................./usr/local/lib/python3.4/site-packages/pandas-0.14.1-py3.4-linux-x86_64.egg/pandas/tools/plotting.py:2954: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "is being cleared", UserWarning)
....................................../usr/local/lib/python3.4/site-packages/matplotlib-1.3.1-py3.4-linux-x86_64.egg/matplotlib/axes.py:4749: UserWarning: No labeled objects found. Use label='...' kwarg on individual plots.
  warnings.warn("No labeled objects found. "
....................................................................................................................................................../usr/local/lib/python3.4/site-packages/matplotlib-1.3.1-py3.4-linux-x86_64.egg/matplotlib/__init__.py:1157: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
.............................................................................................................................................../usr/local/lib/python3.4/site-packages/pandas-0.14.1-py3.4-linux-x86_64.egg/pandas/core/index.py:1023: RuntimeWarning: Cannot compare type 'Timestamp' with type 'str', sort order is undefined for incomparable objects
  "incomparable objects" % e, RuntimeWarning)
................................................../usr/local/lib/python3.4/site-packages/pandas-0.14.1-py3.4-linux-x86_64.egg/pandas/core/index.py:1023: RuntimeWarning: Cannot compare type 'Timestamp' with type 'int', sort order is undefined for incomparable objects
  "incomparable objects" % e, RuntimeWarning)
.....................................................................................................S..............................................................................S.....S................................................................S...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................S.................................................................................................................................................................................................................................S...S.............SSS.........S............SS.............SS.....SSSS..............................................................................................................................................................................................................................S...............................S..........................................................................................................................................................................................................................
======================================================================
ERROR: test_file_like (pandas.io.tests.test_html.TestReadHtml)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/pandas-0.14.1-py3.4-linux-x86_64.egg/pandas/io/tests/test_html.py", line 290, in test_file_like
    df1 = self.read_html(f, '.*Water.*')
  File "/usr/local/lib/python3.4/site-packages/pandas-0.14.1-py3.4-linux-x86_64.egg/pandas/io/tests/test_html.py", line 97, in read_html
    return read_html(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/pandas-0.14.1-py3.4-linux-x86_64.egg/pandas/io/html.py", line 851, in read_html
    parse_dates, tupleize_cols, thousands, attrs, encoding)
  File "/usr/local/lib/python3.4/site-packages/pandas-0.14.1-py3.4-linux-x86_64.egg/pandas/io/html.py", line 714, in _parse
    raise_with_traceback(retained)
  File "/usr/local/lib/python3.4/site-packages/pandas-0.14.1-py3.4-linux-x86_64.egg/pandas/compat/__init__.py", line 705, in raise_with_traceback
    raise exc.with_traceback(traceback)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 21552: ordinal not in range(128)

======================================================================
ERROR: test_string (pandas.io.tests.test_html.TestReadHtml)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/pandas-0.14.1-py3.4-linux-x86_64.egg/pandas/io/tests/test_html.py", line 281, in test_string
    data = f.read()
  File "/usr/local/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 21552: ordinal not in range(128)

======================================================================
ERROR: test_string_io (pandas.io.tests.test_html.TestReadHtml)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/pandas-0.14.1-py3.4-linux-x86_64.egg/pandas/io/tests/test_html.py", line 270, in test_string_io
    data1 = StringIO(f.read())
  File "/usr/local/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 21552: ordinal not in range(128)

======================================================================
FAIL: test_fred (pandas.io.tests.test_data.TestFred)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/pandas-0.14.1-py3.4-linux-x86_64.egg/pandas/util/testing.py", line 1346, in wrapper
    return t(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/pandas-0.14.1-py3.4-linux-x86_64.egg/pandas/io/tests/test_data.py", line 448, in test_fred
    self.assertEqual(int(received), 16535)
AssertionError: 16502 != 16535

----------------------------------------------------------------------
Ran 7352 tests in 556.583s

FAILED (SKIP=227, errors=3, failures=1)
<class 'pandas.tseries.index.DatetimeIndex'>
[2011-01-04, 2011-01-02]
Length: 2, Freq: None, Timezone: None <class 'pandas.tseries.index.DatetimeIndex'>
[2011-01-04, 2011-01-02]
Length: 2, Freq: None, Timezone: None
<class 'pandas.tseries.index.DatetimeIndex'>
[2011-01-04, 2011-01-02]
Length: 2, Freq: None, Timezone: None <class 'pandas.tseries.index.DatetimeIndex'>
[2011-01-04, 2011-01-02]
Length: 2, Freq: None, Timezone: None
<class 'pandas.tseries.index.DatetimeIndex'>
[2011-01-04 00:00:00+09:00, 2011-01-02 00:00:00+09:00]
Length: 2, Freq: None, Timezone: Asia/Tokyo <class 'pandas.tseries.index.DatetimeIndex'>
[2011-01-04 00:00:00+09:00, 2011-01-02 00:00:00+09:00]
Length: 2, Freq: None, Timezone: Asia/Tokyo
<class 'pandas.tseries.index.DatetimeIndex'>
[2011-01-04 00:00:00+09:00, 2011-01-02 00:00:00+09:00]
Length: 2, Freq: None, Timezone: Asia/Tokyo <class 'pandas.tseries.index.DatetimeIndex'>
[2011-01-04 00:00:00+09:00, 2011-01-02 00:00:00+09:00]
Length: 2, Freq: None, Timezone: Asia/Tokyo
zounds!
Warning: discarding nonzero nanoseconds
